'use client';

import { useState } from 'react';

interface Doc {
  id: string;
  title: string;
  slug: string;
  category: string;
  content: string;
  autoGenerated: boolean;
  updatedAt: string;
}

const CATEGORIES = [
  { key: 'overview', label: 'Ops Overview' },
  { key: 'task-manager', label: 'Task Manager' },
  { key: 'org-chart', label: 'Org Chart' },
  { key: 'workspaces', label: 'Workspaces' },
  { key: 'standups', label: 'Standups' },
  { key: 'changelog', label: 'Changelog' },
];

const DOCS: Doc[] = [
  {
    id: 'd-1', title: 'Ops Dashboard Overview', slug: 'overview', category: 'overview', autoGenerated: false, updatedAt: '2026-02-12T22:00:00Z',
    content: `# Ops Dashboard Overview

The Ops Dashboard is Derek's command center for managing his AI agent swarm. Built on Next.js 16 + Supabase, deployed on Vercel at \`dbtech45.com/os\`.

## Architecture

- **Frontend:** Next.js App Router, TypeScript, Tailwind CSS
- **Backend:** Next.js API Routes + Supabase Postgres
- **AI Runtime:** Clawdbot (OpenClaw) for agent orchestration
- **Models:** Anthropic (Opus, Sonnet), Google (Gemini), OpenAI (GPT)
- **Deploy:** Vercel (auto-deploy on push)

## Core Tabs

1. **Task Manager** — Active sessions, model fleet, cron jobs
2. **Morning Brief** — 6-section digital newspaper (markets, sports, tech, local, AI)
3. **Org Chart** — Agent hierarchy with roles and model assignments
4. **Workspaces** — Persistent agent identities and configuration
5. **Standups** — Multi-agent meetings with transcripts and action items
6. **Docs** — Living documentation (this section)

## Key Concepts

- **Agents** run as Clawdbot instances with their own workspaces, memory, and tools
- **Milo** is the COO/orchestrator — all delegation flows through him
- **Sessions** are runtime instances; an agent can have multiple sessions
- **Cron jobs** fire on schedule and spawn isolated agent sessions
- **Standups** are multi-agent conversations logged as transcripts`,
  },
  {
    id: 'd-2', title: 'Agent Roster', slug: 'agent-roster', category: 'overview', autoGenerated: true, updatedAt: '2026-02-12T22:50:00Z',
    content: `# Agent Roster

## Current Agents (9)

| Agent | Role | Primary Model | Status |
|-------|------|---------------|--------|
| **Milo** | COO — Orchestrator | Opus 4.6 | Active |
| **Bobby** | CRO — Trading Advisor | Opus 4.6 | Active |
| **Anders** | CTO — Full Stack Architect | Opus 4.6 | Active |
| **Paula** | CMO — Design Lead | Opus 4.6 | Active |
| **Dwight** | Security & QA | Gemini 3 Flash | Active |
| **Tony** | Restaurant Ops | Gemini 3 Pro | Active |
| **Remy** | Content & Newsletter | Opus 4.6 | Active |
| **Dax** | Social & Hype | Gemini 3 Flash | Active |
| **Wendy** | Growth & Community | Gemini 3 Flash | Active |

## Hierarchy

\`\`\`
Derek (CEO)
└── Milo (COO)
    ├── Anders (CTO)
    │   ├── Backend/Security Division
    │   └── Dwight (QA)
    ├── Paula (CMO)
    │   ├── Remy (Content)
    │   └── Dax (Social)
    └── Bobby (CRO)
        ├── Tony (Restaurant Ops)
        └── Wendy (Community)
\`\`\`

## Gateway Configuration

- **Milo** has his own gateway + heartbeat
- All other agents share Milo's gateway
- Heartbeat enabled: Milo, Bobby, Anders, Paula`,
  },
  {
    id: 'd-3', title: 'Task Manager Guide', slug: 'task-manager-guide', category: 'task-manager', autoGenerated: false, updatedAt: '2026-02-12T22:55:00Z',
    content: `# Task Manager

The Task Manager provides real-time visibility into agent sessions, model usage, and scheduled jobs.

## Summary Header

Five metric cards showing:
- **Running** sessions (green pulse indicator)
- **Idle** sessions
- **Error** sessions (red)
- **Tokens (24h)** — total input + output tokens across all sessions
- **Cost (24h)** — estimated USD cost

## Active Sessions Tab

Table of all running/idle/error sessions with columns:
- Session ID, Agent Name, Status, Model, Last Active, Tokens In/Out, Cost
- Click any row to open the **transcript panel** showing the conversation log

## Model Fleet Tab

Grid of configured LLM models showing:
- Model name, provider, tier (primary/backup)
- Role description (what this model is used for)
- Active session count, token usage, cost
- Which agents are currently using this model

## Cron & Scheduled Jobs Tab

Table of all cron jobs with:
- Job name, description, schedule (human-readable)
- Assigned agent, last status (success/fail)
- Pause/resume and manual trigger buttons

## Integration Points

- Sessions data → Clawdbot \`sessions_list\` API
- Cron data → Clawdbot \`cron list\` command
- Token/cost data → Gateway usage metrics`,
  },
  {
    id: 'd-4', title: 'Model Fleet Configuration', slug: 'model-fleet', category: 'task-manager', autoGenerated: true, updatedAt: '2026-02-12T22:50:00Z',
    content: `# Model Fleet

## Active Models

### Claude Opus 4.6 (Primary)
- **Provider:** Anthropic
- **Role:** Heavy lifting — complex reasoning, architecture, strategy
- **Used by:** Milo, Bobby, Anders, Paula, Remy
- **Cost:** ~$15/1M input tokens, ~$75/1M output tokens

### Claude Opus 4.5 (Backup)
- **Provider:** Anthropic
- **Role:** Fallback when Opus 4.6 hits rate limits
- **Used by:** Milo (fallback), Wendy

### Claude Sonnet 4.5
- **Provider:** Anthropic
- **Role:** Fast output — content generation, summaries
- **Used by:** Paula (design output), Remy (writing)

### Gemini 3 Pro
- **Provider:** Google
- **Role:** Research & deep analysis with grounded search
- **Used by:** Tony, Bobby (research tasks)

### Gemini 3 Flash
- **Provider:** Google
- **Role:** Cheap bulk work — monitoring, classification
- **Used by:** Dwight, Dax, Wendy

### GPT 5.3 Codex
- **Provider:** OpenAI
- **Role:** Code generation via Codex CLI
- **Used by:** Anders (via Codex CLI)`,
  },
  {
    id: 'd-5', title: 'Org Chart Structure', slug: 'org-chart-structure', category: 'org-chart', autoGenerated: true, updatedAt: '2026-02-12T22:50:00Z',
    content: `# Org Chart

## Design Principle

The org chart mirrors a real company structure:
- **Derek** (Human CEO) sets vision and makes final calls
- **Milo** (COO) orchestrates everything — always delegates, never queues
- **Department heads** (Anders/CTO, Paula/CMO, Bobby/CRO) manage their domains
- **Sub-agents** handle specialized tasks within departments

## Update Rules

When structural changes occur (new agent, role change, model swap):
1. The change is logged in \`change_log\` table
2. Milo's workspace is notified
3. A doc update is triggered for this page
4. The org chart UI reflects the change on next load

## Current Structure

See the interactive Org Chart tab for the full tree view with expand/collapse.`,
  },
  {
    id: 'd-6', title: 'Workspace Management', slug: 'workspace-management', category: 'workspaces', autoGenerated: false, updatedAt: '2026-02-12T22:50:00Z',
    content: `# Workspaces

Each agent has a **workspace** — a persistent identity with its own:

## Configuration

- **Soul/Persona** — the system prompt that defines who the agent is
- **Long-term Goals** — what the agent is optimizing for
- **Model Configuration** — primary, backup, and special-purpose models
- **Model Routing Rules** — conditional logic for which model handles what
- **Tools** — what external tools/APIs the agent can call
- **Memory** — enabled/disabled, namespace, retention period

## Gateway

- **Milo** has his own gateway (independent heartbeat, independent restarts)
- All other agents share Milo's gateway
- Agents with \`heartbeatEnabled: true\` get periodic check-ins

## CRUD Operations

From the Workspaces tab:
- View any workspace's full configuration
- Edit soul/persona and long-term goals
- Attach or detach tools
- Configure model routing rules
- Changes are logged and trigger doc updates`,
  },
  {
    id: 'd-7', title: 'Standups & AI Meetings', slug: 'standups-guide', category: 'standups', autoGenerated: false, updatedAt: '2026-02-12T22:50:00Z',
    content: `# Standups & AI Meetings

## What They Are

Standups are scheduled multi-agent conversations where agents discuss status, blockers, and priorities — without human intervention.

## Creating a Standup

Define:
- **Title** and description/topic
- **Participants** (select from agent roster)
- **Schedule** (cron string for recurring, or manual trigger)

## How They Run

1. At the scheduled time (or manual trigger), Clawdbot spawns a shared session
2. Each participating agent joins and contributes based on their role
3. The conversation is logged as a transcript
4. After completion, action items are extracted and assigned

## Viewing Results

- **Past Standups** list shows date, participants, summary, and action item progress
- Click any run to see the full transcript in a conversation layout
- **Action Items** panel with checkboxes for tracking completion

## Audio (Optional)

Standups can be rendered as audio using Edge TTS and sent as Telegram notifications with a link to the audio file.`,
  },
  {
    id: 'd-8', title: 'Changelog', slug: 'changelog', category: 'changelog', autoGenerated: true, updatedAt: '2026-02-12T23:00:00Z',
    content: `# Changelog

## 2026-02-12

### Added
- **Task Manager** tab — active sessions, model fleet, cron jobs with transcript viewer
- **Org Chart** tab — collapsible tree view with detail panel
- **Workspaces** tab — 9 agent workspace configs with soul/persona editing
- **Standups** tab — past runs with transcripts and action items
- **Docs** tab — living documentation with sidebar nav
- **Second Brain** — replaced Memory Bank in Operations section
- **Newsletter** components — premium gradient cards (Signal & Noise + The Operator)
- **ThePit** component — scrolling ticker, live signals, stats cards
- **DB Schema** — full Postgres schema for Ops dashboard (14 tables)

### Fixed
- Second Brain search crash on Vercel (filesystem paths don't exist in serverless)
- Newsletter route conflict (dashboard vs root routes)
- Next.js CVE vulnerability (updated to latest)

### Changed
- Morning Brief expanded to 6-section digital newspaper
- Sports section rebuilt with ESPN API (real scores + standings)
- Homepage V2 with cleaner component structure

## 2026-02-11

### Added
- dbtech45 homepage V2 deployed
- Supabase backend (7 tables)
- Morning Brief multi-section architecture

## 2026-02-10

### Added
- Derek OS V3 with real data connections
- Activity dashboard with live stats`,
  },
];

export default function DocsPage() {
  const [selectedDoc, setSelectedDoc] = useState<Doc>(DOCS[0]);

  const docsByCategory = CATEGORIES.map(cat => ({
    ...cat,
    docs: DOCS.filter(d => d.category === cat.key),
  })).filter(cat => cat.docs.length > 0);

  // Simple markdown renderer
  const renderMarkdown = (md: string) => {
    const lines = md.split('\n');
    const elements: React.ReactElement[] = [];

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];

      if (line.startsWith('# ')) {
        elements.push(<h1 key={i} style={{ color: '#FAFAFA', fontSize: '1.5rem', fontWeight: 700, margin: '0 0 1rem', borderBottom: '1px solid #27272A', paddingBottom: '0.75rem' }}>{line.slice(2)}</h1>);
      } else if (line.startsWith('## ')) {
        elements.push(<h2 key={i} style={{ color: '#FAFAFA', fontSize: '1.125rem', fontWeight: 600, margin: '1.5rem 0 0.75rem' }}>{line.slice(3)}</h2>);
      } else if (line.startsWith('### ')) {
        elements.push(<h3 key={i} style={{ color: '#F59E0B', fontSize: '0.95rem', fontWeight: 600, margin: '1.25rem 0 0.5rem' }}>{line.slice(4)}</h3>);
      } else if (line.startsWith('- **')) {
        const match = line.match(/^- \*\*(.+?)\*\*\s*[-—]?\s*(.*)/);
        if (match) {
          elements.push(
            <div key={i} style={{ display: 'flex', gap: '0.5rem', padding: '0.25rem 0', marginLeft: '1rem' }}>
              <span style={{ color: '#F59E0B' }}>•</span>
              <span><span style={{ color: '#FAFAFA', fontWeight: 600 }}>{match[1]}</span> {match[2] && <span style={{ color: '#A1A1AA' }}> — {match[2]}</span>}</span>
            </div>
          );
        }
      } else if (line.startsWith('- ')) {
        elements.push(
          <div key={i} style={{ display: 'flex', gap: '0.5rem', padding: '0.25rem 0', marginLeft: '1rem', color: '#A1A1AA', fontSize: '0.875rem' }}>
            <span style={{ color: '#52525B' }}>•</span>
            <span>{line.slice(2)}</span>
          </div>
        );
      } else if (line.startsWith('|') && line.includes('|')) {
        // Table row
        const cells = line.split('|').filter(c => c.trim()).map(c => c.trim());
        if (cells.some(c => c.match(/^-+$/))) continue; // separator
        const isHeader = i > 0 && lines[i + 1]?.includes('---');
        elements.push(
          <div key={i} style={{ display: 'grid', gridTemplateColumns: `repeat(${cells.length}, 1fr)`, gap: '0.5rem', padding: '0.5rem 0.75rem', background: isHeader ? '#0A0A0A' : 'transparent', borderBottom: '1px solid #1A1A1C' }}>
            {cells.map((cell, j) => (
              <span key={j} style={{ color: isHeader ? '#71717A' : '#A1A1AA', fontSize: '0.8rem', fontWeight: isHeader ? 600 : 400 }} dangerouslySetInnerHTML={{ __html: cell.replace(/\*\*(.+?)\*\*/g, '<strong style="color:#FAFAFA">$1</strong>') }} />
            ))}
          </div>
        );
      } else if (line.startsWith('```')) {
        // Code block
        const codeLines: string[] = [];
        i++;
        while (i < lines.length && !lines[i].startsWith('```')) {
          codeLines.push(lines[i]);
          i++;
        }
        elements.push(
          <pre key={`code-${i}`} style={{ background: '#0A0A0A', border: '1px solid #1A1A1C', borderRadius: '8px', padding: '1rem', margin: '0.75rem 0', overflow: 'auto', fontFamily: "'JetBrains Mono', monospace", fontSize: '0.8rem', color: '#A1A1AA', lineHeight: 1.6 }}>
            {codeLines.join('\n')}
          </pre>
        );
      } else if (line.trim() === '') {
        elements.push(<div key={i} style={{ height: '0.5rem' }} />);
      } else {
        elements.push(<p key={i} style={{ color: '#A1A1AA', fontSize: '0.875rem', lineHeight: 1.6, margin: '0.25rem 0' }} dangerouslySetInnerHTML={{ __html: line.replace(/\*\*(.+?)\*\*/g, '<strong style="color:#FAFAFA">$1</strong>').replace(/`(.+?)`/g, '<code style="background:#1A1A1C;padding:0.125rem 0.375rem;border-radius:3px;font-family:JetBrains Mono,monospace;font-size:0.8rem;color:#F59E0B">$1</code>') }} />);
      }
    }

    return elements;
  };

  return (
    <div style={{ display: 'flex', height: 'calc(100vh - 64px)', fontFamily: "'Inter', sans-serif" }}>
      {/* Sidebar */}
      <div style={{ width: 260, borderRight: '1px solid #27272A', padding: '1.5rem 1rem', overflowY: 'auto', flexShrink: 0 }}>
        <div style={{ marginBottom: '1.5rem' }}>
          <span style={{ color: '#F59E0B', fontFamily: "'JetBrains Mono', monospace", fontSize: '0.75rem' }}>&gt; docs</span>
          <h2 style={{ color: '#FAFAFA', fontSize: '1rem', fontWeight: 700, margin: '0.25rem 0 0' }}>Documentation</h2>
        </div>

        {docsByCategory.map(cat => (
          <div key={cat.key} style={{ marginBottom: '1.25rem' }}>
            <h3 style={{ color: '#52525B', fontSize: '0.7rem', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '0.375rem', padding: '0 0.5rem' }}>{cat.label}</h3>
            {cat.docs.map(doc => (
              <button
                key={doc.id}
                onClick={() => setSelectedDoc(doc)}
                style={{
                  display: 'block', width: '100%', textAlign: 'left',
                  background: selectedDoc.id === doc.id ? '#1A1A1C' : 'transparent',
                  border: 'none', borderRadius: '6px',
                  padding: '0.5rem 0.75rem', marginBottom: '2px',
                  color: selectedDoc.id === doc.id ? '#FAFAFA' : '#71717A',
                  fontSize: '0.8rem', cursor: 'pointer', transition: 'all 0.1s',
                }}
                onMouseEnter={e => { if (selectedDoc.id !== doc.id) e.currentTarget.style.background = '#111115'; }}
                onMouseLeave={e => { if (selectedDoc.id !== doc.id) e.currentTarget.style.background = 'transparent'; }}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  <span>{doc.title}</span>
                  {doc.autoGenerated && <span style={{ width: 6, height: 6, borderRadius: '50%', background: '#3B82F6', flexShrink: 0 }} title="Auto-generated" />}
                </div>
              </button>
            ))}
          </div>
        ))}
      </div>

      {/* Content */}
      <div style={{ flex: 1, padding: '2rem 3rem', overflowY: 'auto', maxWidth: 900 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.5rem' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            {selectedDoc.autoGenerated && (
              <span style={{ padding: '0.2rem 0.5rem', borderRadius: '4px', fontSize: '0.65rem', background: '#3B82F620', color: '#3B82F6', border: '1px solid #3B82F640' }}>Auto-generated</span>
            )}
            <span style={{ color: '#3F3F46', fontSize: '0.75rem' }}>
              Updated {new Date(selectedDoc.updatedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
            </span>
          </div>
        </div>
        {renderMarkdown(selectedDoc.content)}
      </div>
    </div>
  );
}
