// ─── Ops Dashboard — Core Types & DB Schema ─────────────────────────────
// Maps to Postgres tables in Supabase (dbtech45-os project)
// Schema: public

// ─── Models ──────────────────────────────────────────────────────────────

export interface Model {
  id: string;
  displayName: string;
  provider: 'anthropic' | 'openai' | 'google' | 'meta' | 'other';
  roleDescription: string;
  tier: 'primary' | 'backup';
  apiKeyEnv: string;        // env var name, e.g. ANTHROPIC_API_KEY
  maxContextTokens: number;
  costPerInputToken: number;  // USD
  costPerOutputToken: number;
  enabled: boolean;
  createdAt: string;
  updatedAt: string;
}

// ─── Agents & Org Chart ──────────────────────────────────────────────────

export interface Agent {
  id: string;
  name: string;
  role: string;               // e.g. "CEO", "COO", "CTO"
  title: string;              // e.g. "Chief Technology Officer"
  responsibilities: string[];
  parentAgentId: string | null;
  department?: string;
  division?: string;
  primaryModelId: string;
  backupModelId?: string;
  tools: string[];
  isHuman: boolean;
  avatarUrl?: string;
  createdAt: string;
  updatedAt: string;
}

// ─── Workspaces ──────────────────────────────────────────────────────────

export interface Workspace {
  id: string;
  agentId: string;
  name: string;
  description: string;
  primaryModelId: string;
  backupModelId?: string;
  specialModelId?: string;
  hasOwnGateway: boolean;
  heartbeatEnabled: boolean;
  tools: string[];
  memoryEnabled: boolean;
  memoryNamespace: string;
  memoryRetentionDays: number;
  soulPrompt: string;          // persona / long-term goals
  longTermGoals: string[];
  modelRoutingRules: ModelRoutingRule[];
  status: 'active' | 'inactive' | 'maintenance';
  lastHeartbeat?: string;
  createdAt: string;
  updatedAt: string;
}

export interface ModelRoutingRule {
  condition: string;           // e.g. "token_count > 100000"
  modelId: string;
  priority: number;
}

// ─── Sessions ────────────────────────────────────────────────────────────

export interface Session {
  id: string;
  agentId: string;
  agentName: string;
  modelId: string;
  status: 'running' | 'idle' | 'error' | 'completed';
  startedAt: string;
  lastActivityAt: string;
  completedAt?: string;
  tokensIn: number;
  tokensOut: number;
  costEstimate: number;
  errorMessage?: string;
  metadata?: Record<string, any>;
}

export interface Message {
  id: string;
  sessionId: string;
  role: 'user' | 'assistant' | 'system' | 'tool';
  content: string;
  agentId?: string;
  modelId?: string;
  tokensUsed?: number;
  createdAt: string;
}

// ─── Cron / Scheduled Jobs ───────────────────────────────────────────────

export interface CronJob {
  id: string;
  name: string;
  description: string;
  schedule: string;
  agentId: string;
  enabled: boolean;
  lastRunAt?: string;
  lastStatus: 'success' | 'fail' | 'pending' | 'running';
  nextRunAt?: string;
  config?: Record<string, any>;
  createdAt: string;
  updatedAt: string;
}

export interface JobRun {
  id: string;
  jobId: string;
  status: 'success' | 'fail' | 'running';
  startedAt: string;
  completedAt?: string;
  output?: string;
  errorMessage?: string;
  tokensUsed?: number;
  costEstimate?: number;
}

// ─── Standups / AI Meetings ──────────────────────────────────────────────

export interface Standup {
  id: string;
  title: string;
  description: string;
  topic?: string;
  participantAgentIds: string[];
  schedule?: string;           // cron string or null for manual
  isRecurring: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface StandupRun {
  id: string;
  standupId: string;
  status: 'scheduled' | 'running' | 'completed' | 'failed';
  startedAt: string;
  completedAt?: string;
  summary?: string;
  transcript: StandupMessage[];
  audioUrl?: string;
  createdAt: string;
}

export interface StandupMessage {
  id: string;
  standupRunId: string;
  agentId: string;
  agentName: string;
  content: string;
  timestamp: string;
  order: number;
}

export interface ActionItem {
  id: string;
  standupRunId: string;
  description: string;
  ownerAgentId: string;
  ownerAgentName: string;
  status: 'pending' | 'in_progress' | 'done';
  linkedTaskId?: string;
  linkedSessionId?: string;
  createdAt: string;
  completedAt?: string;
}

// ─── Docs ────────────────────────────────────────────────────────────────

export interface Doc {
  id: string;
  title: string;
  slug: string;
  content: string;             // markdown
  category: 'overview' | 'task-manager' | 'org-chart' | 'workspaces' | 'standups' | 'changelog';
  order: number;
  autoGenerated: boolean;
  lastGeneratedBy?: string;    // agent ID that auto-generated
  createdAt: string;
  updatedAt: string;
}

// ─── Changelog / Audit Log ───────────────────────────────────────────────

export interface ChangeLog {
  id: string;
  entityType: 'agent' | 'workspace' | 'model' | 'job' | 'standup' | 'doc';
  entityId: string;
  action: 'created' | 'updated' | 'deleted';
  changes: Record<string, { old: any; new: any }>;
  triggeredBy: string;         // agent ID or 'human'
  docUpdateRequired: boolean;
  docUpdated: boolean;
  createdAt: string;
}

// ─── Configuration ───────────────────────────────────────────────────────

export interface OpsConfig {
  id: string;
  key: string;
  value: string;
  description?: string;
  updatedAt: string;
}
