'use client';

import { useState } from 'react';
import { Upload, Loader2, RefreshCw, Download, Eye } from 'lucide-react';

export default function BrandChameleonPage() {
  const [uploading, setUploading] = useState(false);
  const [analyzing, setAnalyzing] = useState(false);
  const [logoUrl, setLogoUrl] = useState<string | null>(null);
  const [brandSystem, setBrandSystem] = useState<any>(null);
  const [previewMode, setPreviewMode] = useState(false);

  const handleLogoUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setUploading(true);
    const reader = new FileReader();
    reader.onloadend = () => {
      setLogoUrl(reader.result as string);
      analyzeBrand(reader.result as string);
    };
    reader.readAsDataURL(file);
  };

  const analyzeBrand = async (base64Image: string) => {
    setAnalyzing(true);
    
    try {
      const response = await fetch('/api/analyze-brand', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ logo: base64Image }),
      });
      
      const data = await response.json();
      setBrandSystem(data);
    } catch (error) {
      console.error('Brand analysis failed:', error);
    } finally {
      setUploading(false);
      setAnalyzing(false);
    }
  };

  const applyBrand = () => {
    if (!brandSystem) return;
    
    // Store in localStorage for demo
    localStorage.setItem('custom-brand', JSON.stringify(brandSystem));
    setPreviewMode(true);
    
    // In production, this would update a global theme context
    // and re-render the entire OS with new brand colors
  };

  const resetBrand = () => {
    localStorage.removeItem('custom-brand');
    setPreviewMode(false);
    setBrandSystem(null);
    setLogoUrl(null);
  };

  const downloadBrandKit = () => {
    if (!brandSystem) return;
    
    const brandKit = `# Brand System
Generated by Brand Chameleon

## Colors
Primary: ${brandSystem.colors?.primary || '#F59E0B'}
Secondary: ${brandSystem.colors?.secondary || '#10ca78'}
Accent: ${brandSystem.colors?.accent || '#EC4899'}
Background: ${brandSystem.colors?.background || '#000000'}
Text: ${brandSystem.colors?.text || '#FFFFFF'}

## Typography
Heading: ${brandSystem.typography?.heading || 'Space Grotesk'}
Body: ${brandSystem.typography?.body || 'Inter'}
Mono: ${brandSystem.typography?.mono || 'JetBrains Mono'}

## Usage
Import this system into your design tools or code.
Tailwind config available on request.
`;

    const blob = new Blob([brandKit], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'brand-system.txt';
    a.click();
  };

  // Use custom brand if in preview mode
  const activeBrand = previewMode && brandSystem ? brandSystem.colors : {
    primary: '#F59E0B',
    background: '#000000',
    text: '#FFFFFF',
  };

  return (
    <div style={{ 
      padding: '30px', 
      background: activeBrand.background || '#000', 
      minHeight: '100vh',
      fontFamily: "'Inter', system-ui, sans-serif",
      transition: 'all 0.5s ease',
    }}>
      <div style={{ maxWidth: '1200px', margin: '0 auto' }}>
        {/* Header */}
        <div style={{ marginBottom: '30px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <h1 style={{ 
              fontSize: '24px', 
              fontWeight: 700, 
              color: activeBrand.text || '#fff',
              marginBottom: '8px',
            }}>
              Brand Chameleon
            </h1>
            <p style={{ fontSize: '14px', color: '#737373' }}>
              Upload a logo. Watch Mission Control transform to match your brand.
            </p>
          </div>
          
          {previewMode && (
            <button
              onClick={resetBrand}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: '8px',
                padding: '10px 16px',
                background: '#222',
                border: `1px solid ${activeBrand.primary}`,
                borderRadius: '8px',
                color: activeBrand.text,
                fontSize: '14px',
                fontWeight: 600,
                cursor: 'pointer',
              }}
            >
              <RefreshCw size={16} />
              Reset to Default
            </button>
          )}
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: logoUrl ? '1fr 1fr' : '1fr', gap: '30px' }}>
          {/* Upload Zone */}
          <div>
            <label 
              htmlFor="logo-upload"
              style={{
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                justifyContent: 'center',
                minHeight: '400px',
                background: '#111',
                border: `2px dashed ${logoUrl ? activeBrand.primary : '#333'}`,
                borderRadius: '12px',
                cursor: uploading ? 'not-allowed' : 'pointer',
                transition: 'all 0.2s ease',
                position: 'relative',
                overflow: 'hidden',
              }}
            >
              <input
                id="logo-upload"
                type="file"
                accept="image/*"
                onChange={handleLogoUpload}
                disabled={uploading}
                style={{ display: 'none' }}
              />
              
              {logoUrl ? (
                <img 
                  src={logoUrl} 
                  alt="Uploaded logo"
                  style={{ 
                    maxWidth: '80%', 
                    maxHeight: '300px', 
                    objectFit: 'contain',
                  }}
                />
              ) : (
                <>
                  {uploading ? (
                    <Loader2 size={48} color="#F59E0B" style={{ animation: 'spin 1s linear infinite' }} />
                  ) : (
                    <Upload size={48} color="#737373" />
                  )}
                  <div style={{ 
                    marginTop: '16px', 
                    fontSize: '16px', 
                    fontWeight: 600, 
                    color: '#fff',
                  }}>
                    {uploading ? 'Uploading...' : 'Drop logo here'}
                  </div>
                  <div style={{ fontSize: '13px', color: '#737373', marginTop: '8px' }}>
                    PNG, JPG, SVG supported
                  </div>
                </>
              )}
            </label>

            {logoUrl && (
              <button
                onClick={() => {
                  setLogoUrl(null);
                  setBrandSystem(null);
                  setPreviewMode(false);
                }}
                style={{
                  marginTop: '16px',
                  width: '100%',
                  padding: '12px',
                  background: '#222',
                  border: '1px solid #333',
                  borderRadius: '8px',
                  color: '#fff',
                  fontSize: '14px',
                  fontWeight: 600,
                  cursor: 'pointer',
                }}
              >
                Upload Different Logo
              </button>
            )}
          </div>

          {/* Brand System Preview */}
          {logoUrl && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
              {analyzing ? (
                <div style={{
                  background: '#111',
                  border: '1px solid #222',
                  borderRadius: '12px',
                  padding: '40px',
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'center',
                  gap: '16px',
                }}>
                  <Loader2 size={40} color={activeBrand.primary} style={{ animation: 'spin 1s linear infinite' }} />
                  <div style={{ fontSize: '16px', fontWeight: 600, color: '#fff' }}>
                    Extracting brand DNA...
                  </div>
                  <div style={{ fontSize: '13px', color: '#737373', textAlign: 'center' }}>
                    Analyzing colors, typography, and visual identity
                  </div>
                </div>
              ) : brandSystem ? (
                <>
                  {/* Color Palette */}
                  <div style={{
                    background: '#111',
                    border: `1px solid ${previewMode ? activeBrand.primary : '#222'}`,
                    borderRadius: '12px',
                    padding: '20px',
                  }}>
                    <h3 style={{ fontSize: '16px', fontWeight: 600, color: activeBrand.text, marginBottom: '16px' }}>
                      Brand Colors
                    </h3>
                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '12px' }}>
                      {Object.entries(brandSystem.colors || {}).map(([name, hex]: [string, any]) => (
                        <div key={name} style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                          <div style={{
                            height: '60px',
                            borderRadius: '8px',
                            background: hex,
                            border: '1px solid #333',
                          }} />
                          <div style={{ fontSize: '11px', color: '#737373', textTransform: 'capitalize' }}>
                            {name}
                          </div>
                          <div style={{ fontSize: '10px', color: '#555', fontFamily: "'JetBrains Mono', monospace" }}>
                            {hex}
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Typography */}
                  {brandSystem.typography && (
                    <div style={{
                      background: '#111',
                      border: `1px solid ${previewMode ? activeBrand.primary : '#222'}`,
                      borderRadius: '12px',
                      padding: '20px',
                    }}>
                      <h3 style={{ fontSize: '16px', fontWeight: 600, color: activeBrand.text, marginBottom: '16px' }}>
                        Typography System
                      </h3>
                      <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                        <div>
                          <div style={{ fontSize: '12px', color: '#737373', marginBottom: '4px' }}>Headings</div>
                          <div style={{ fontSize: '18px', fontWeight: 700, color: activeBrand.text, fontFamily: brandSystem.typography.heading }}>
                            {brandSystem.typography.heading}
                          </div>
                        </div>
                        <div>
                          <div style={{ fontSize: '12px', color: '#737373', marginBottom: '4px' }}>Body</div>
                          <div style={{ fontSize: '14px', color: activeBrand.text, fontFamily: brandSystem.typography.body }}>
                            {brandSystem.typography.body}
                          </div>
                        </div>
                      </div>
                    </div>
                  )}

                  {/* Actions */}
                  <div style={{ display: 'flex', gap: '12px' }}>
                    {!previewMode ? (
                      <button
                        onClick={applyBrand}
                        style={{
                          flex: 1,
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent: 'center',
                          gap: '8px',
                          padding: '14px',
                          background: activeBrand.primary,
                          border: 'none',
                          borderRadius: '8px',
                          color: '#000',
                          fontSize: '14px',
                          fontWeight: 600,
                          cursor: 'pointer',
                        }}
                      >
                        <Eye size={16} />
                        Preview Live
                      </button>
                    ) : (
                      <button
                        onClick={downloadBrandKit}
                        style={{
                          flex: 1,
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent: 'center',
                          gap: '8px',
                          padding: '14px',
                          background: '#222',
                          border: `1px solid ${activeBrand.primary}`,
                          borderRadius: '8px',
                          color: activeBrand.text,
                          fontSize: '14px',
                          fontWeight: 600,
                          cursor: 'pointer',
                        }}
                      >
                        <Download size={16} />
                        Download Brand Kit
                      </button>
                    )}
                  </div>
                </>
              ) : null}
            </div>
          )}
        </div>

        {/* Preview Notice */}
        {previewMode && (
          <div style={{
            marginTop: '30px',
            padding: '16px 20px',
            background: activeBrand.primary + '20',
            border: `1px solid ${activeBrand.primary}`,
            borderRadius: '8px',
            display: 'flex',
            alignItems: 'center',
            gap: '12px',
          }}>
            <Eye size={20} color={activeBrand.primary} />
            <div>
              <div style={{ fontSize: '14px', fontWeight: 600, color: activeBrand.text }}>
                Live Preview Mode
              </div>
              <div style={{ fontSize: '12px', color: '#737373', marginTop: '2px' }}>
                This page is now styled with your brand. Navigate to other OS pages to see the full effect. (Demo: only this page updates)
              </div>
            </div>
          </div>
        )}
      </div>

      <style jsx>{`
        @keyframes spin {
          from { transform: rotate(0deg); }
          to { transform: rotate(360deg); }
        }
      `}</style>
    </div>
  );
}
